#!/bin/bash
echo "total 36
drwxr-xr-x 1 enghasssan enghasssan   512 Sep  5 05:30 .
drwxr-xr-x 1 enghasssan enghasssan   512 Sep  5 02:36 ..
-rw------- 1 enghasssan enghasssan  4096 Sep  5 03:01 .0-hell0_world.swp
-rw------- 1 enghasssan enghasssan 12288 Sep  5 02:44 .README.md.swp
-rw------- 1 enghasssan enghasssan 12288 Sep  5 02:42 .swp
-rwxr--r-- 1 enghasssan enghasssan    32 Sep  5 03:07 0-hello_world
-rwxr--r-- 1 enghasssan enghasssan    28 Sep  5 03:37 1-confused_smiley
-rwxr--r-- 1 enghasssan enghasssan    29 Sep  5 04:18 2-hellofile
-rwxr--r-- 1 enghasssan enghasssan    40 Sep  5 04:22 3-twofiles
-rwxr--r-- 1 enghasssan enghasssan    35 Sep  5 04:27 4-lastlines
-rwxr--r-- 1 enghasssan enghasssan    35 Sep  5 04:28 5-firstlines
-rwxr--r-- 1 enghasssan enghasssan    40 Sep  5 04:37 6-third_line
-rwxr--r-- 1 enghasssan enghasssan    78 Sep  5 05:03 7-file
-rwxr--r-- 1 enghasssan enghasssan    43 Sep  5 05:28 8-cwd_state
-rw-r--r-- 1 enghasssan enghasssan    87 Sep  5 02:46 README.md" > ls_cwd_content
